name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      # Image with database for SQLProvider
      postgres:
        image: postgres
        volumes: 
          - /docker-entrypoint-initdb.d:${{ github.workspace }}/scripts/database_init
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: mahjong
        options: >-
          --name posttest
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: docker exec posttest ls
    - name: ls init
      run: docker exec posttest ls docker-entrypoint-initdb.d
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.103
    - name: Install tools
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet restore
    - name: Run FAKE
      run: dotnet fake build
    - name: Run Server tests
      run: dotnet run --project tests/Server --framework netcoreapp3.1
      
